---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgA0lcrBpWi+WpbTX1P4qb1IHsx4FA4UoUBpwheB9neLTVMVN+fOrhzkIOA25oYhoWS6sZpuxUebNsGt3R3plSZgZlT5coxltcOlzetfR709vfk/lFGtApzD8dOqxRjgsNMe3szEqX6THYsBtX6T8+Emk+qhCVqt68ddTxMktctEtsSRckHtVjOAC7LCjAvXGGD5ZpBQfq4GlEDk7nbbOGkCI6c5VLlo2aOy6sIwNWl63T9xy7KRNKtxOsuPhyJhTNHQa7r1jxNE0ogHmkBPZMxZdxARO+DECPieFtu1gtvqdm4TCgaTPwUE6yv7CTCfldP0aVxOxk0bYwsc1idHWuepkTowWWkCiB5ZZieQNOvEQPZyvmIZZvCuMrwdKM/BsMrPuULzludfBW9y94NiW3twSxZS8tK6nHUdLSKmqp9Xsk2flpqHSZT5ztuGuMyk5pZqo5aS4swZ2BlMqkKWum70LsmLbBs97S+USmAfhTLq9DBKOrLqzbL0AsVzJ5qGg5wLD6SzPc2Lho/fDXrB3nGFEGYhR50p4nkj9VxqeHWn4ImukktaYoT4k6ruoOfexieIwldxR2S11lSPvrwQkt56raDsatAJevSoG+od+4CUFiRWEV7RYLxENS7Kk0RNk80qg6RwTN0WssZ49PYBgc1pGmxVZ01XE71l5tGyYw6lG96VwGGaBr5887U04TAs3kDUSMpa/U0w1a8CasPDGauIwg==
    client_secret: AgCCqyaWe7eMt4eihHkE24Bhl4G5g0NmUA8xOgdBtkci/uygHaHXoTjPKYgVYRPmWxSIj3gQU9HFbPjS6N5Sxr1IhZrZWzoQX4a/jj25cAl4oCJAxBOytmF0/lK+eUgqjll4ZvlkUURDLJusdUozr8xeObU4AbS2gNG2JiWF87BfmyxRXMldaGCnXwp9M0MkIPfo3S1A5L7VQovxmVYiVTR/MFJLsBsbEI+zyrqKk65I7NO9A2GCMHMgMVBHemjX1Qf/QHc29CAsfKk+zei72vXy1eLyDF8wIUlrykPep4LAQyyGjv+tKZDJUE1uZzek+Y1UwPZsWeE7qzpkoEDd7XbF3PbB1aNwFw/ekKBhVw3cleKxWuf0wFxEbST0kSOr2SLbeZ/CUtUukX2XAGQ5H1IlieI3GiQJNLAIdDEUVFjeVJ5/lq9nEp6/KBiCnrVcPmSPD0zmZnewc8VPyBmhkH5687OCRUeunm/JqznhKjLXtuOqqMVrWjIYtztDjqD51G+BlcLoyZdIyTmX9n6OESq+XIJHAixGnkU3DuHN7CoajcTI1OkcBO5nPVhIfaIH/MFx0f7xUrNYvpXmEgbxID3lROcNht4b5ABhfGIXDPRFQcJFn+cwz9Hdj2NGg8u+XBFbVZ7WFC1vcRNdVXiKR8Lzj7nBruFavxAtqLt5ch+xyugJzPkSLr3ovk2fBg5WTIn1tM2yAFUrj2VqFFPVvdRIwTvqc6cHKoalRyPu1pqnCgZK5sZXrQEwR+rBzdpusvr4Mu8fo00esQVTgcH18i3C
  template:
    metadata:
      name: operator-oauth
      namespace: tailscale
    type: Opaque
