---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: velero-r2-credentials
  namespace: velero
spec:
  encryptedData:
    cloud: AgCAqCl7R+0qAvvvkb2w0PC/hwwpX6VOK8PuzmIwi9XljVFzRpxZzaysYHytfRcyPlrNZ4w3ZSbmGf3LM96fUK2P1BwadNfchBGmFgcKdYRglyxI5Lu19BqMHMwskkwHj1A9TUC9HTONAAd5mJ6Qj9glpjUsihbh8syUFEUAzk7D+JmgEZB4C+dhx+QC2PZQLUA3/ZWlLM7uAuGJ3H+DTSSX+nnKcOTWLkqQdcYekHWENfoLUrPphkezkhcVKsxicTfhmj1lOfFRurs4PERkuq++dzlkfocgBN24Apd8V7w3tqPkoOBlhMhlM0K9LXgmBLWNK0FxJT2DWE0S1e+Lpk66LhOLDqkhfZI/p37Lf5q7fH3ci4ve0VDnXysD+8CCOn5+Xs77FvJ+bkk2k0tc4OyrOVIbIDPf4Zu83ZCFCefQSooaPiM6o8VsI1ydT8xwMYf+zC+x3lYXRESsCjyj58F3kNrP2M5RZKTFHH9Cn4qSM/Jf1MyohWJFq8idFD5gJVkl5n4HoqymEANU7zH81qu3uuCtsQ9ojDmwBELZ9wxyLWP19flZ69K2Zmj31zZwIw56IXrR2JE+ixhaz2cmenVoGRoQjtpUMsA5mK3rgcSqYQX3OmAtOGc18FNDRdZD3XTqcwpVpMribMl+4A0YX0iCl7YclmZz1V+ESUe/+SfOk8sOKCwWHVmv2vDNr2lo4okj1H3Fze/Y71aqWuK1UNrAPboobUJ7ELW9JotjFAw0TCFMigET52BsR/6Zbv0KweX9MKaRV0O4bp7NX4O3ssXSBERsqkcZz6WpCDO3YxItis36ds6FYfeQSr4B4YSoqL7/sLWKfagiN9sfW/HkqjWIDqu9XQ5btHhO1VxDORSOxpiYjcxaY25iafxPnK1BmJeRA+AQ
  template:
    metadata:
      name: velero-r2-credentials
      namespace: velero
    type: Opaque
