---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: velero-repo-credentials
  namespace: velero
spec:
  encryptedData:
    repository-password: AgCoXjPHfnWAONhpzUmliyVz2c6UaNwTNvk2o0fKXXmKuGkEalPX/SgR2PUwhFbdb+SyDXe4qY5WUca2LJHCmCNIzElf0FD6thPFdXYZ52LXmeSf3NQgcnAg/6nEAMGXgRr2IDqt/czndkQbdVmWMNRcBbGOeB1ITwTXopgfFfEFZ+R1J26VgzH/If3GctvvbRK38pCRXrn7WDo3yclZYOmExb3W6KB6QhbsX9uPmV8qUAlQMILhBUXF754YOBdJJ0zguaEEMEQ1Mucky+lsIF6c+QOPJYlpfo9mp5S+rCZZe7xrqXwSffUBPUL6wI5K2/bgPdMpAd2j+At5Ss3Lg00V3ozWI8zaJ3QuC+J4G+Id3MYKrm7jbgTmy93I4z0f9OkeOr50ZmzH9bJiDpeZPDrtqDNXLK3XQheZgucMWHUax5PoCZujye84zu0BBVaP0jG/GRIHYbW5auranUvqnrOR5hNcOc6OnHraYkmh/BOtC1WcH10coJ8eB8ePLTw/qjkyCBh9zD8ZWSDHnMBCpSUhvnCe2ad4JO4n9cWI+mjv08Hjc2PVq+uCGXvV0V1GT2kmfjG8M+eS4i/jCVu/zWjSYwtvXlDp/WXRIrjDRLDHMgELYouPFNis5icvO35gjUIjQqxjldZ62ESoEwV7bu64V+LJhitrSdg3Q+PeV/DfmgEx7Wz83xbQ7unPK6usqQ5trCgulRsKNU2Jm3HFh6Q=
  template:
    metadata:
      name: velero-repo-credentials
      namespace: velero
    type: Opaque
